### PR TITLE
correct bitrate range

### PR DESCRIPTION
**Pull request by greenbigfrog**

### CODE REVIEW

**Comment by Snazzah** [comment]
Can you add the bit about the VIP servers?

**Comment by greenbigfrog** [comment]
What do you exactly mean?

(If you give me collabrator on your fork I could directly commit saving you the extra step of needing to merge each PR)

**Comment by Snazzah** [comment]
`the bitrate (in bits) of the voice channel; 8000 to 96000 (128000 for VIP servers)`

**Comment by greenbigfrog** [comment]
I'll just stash that commit and commit a new one... Thanks!

**Pull request closed without merging**
